#!/usr/bin/env bash
#
# Copyright 2022-2026 Virogu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

# get the installation path
install_path=$2

# set ownership and permissions of the adb file
# chown root:root "$install_path/lib/app/resources/app/adb"
chmod +x "$install_path/lib/app/resources/app/adb"
chmod +x "$install_path/lib/app/resources/app/scrcpy"
chmod +x "$install_path/lib/app/resources/app/scrcpy-main"

# create the log directory and set permissions
mkdir -p "$install_path/bin/log/rolling"
chmod -R a+rw "$install_path/bin/log"

mkdir -p "$install_path/bin/app"
chmod -R a+rw "$install_path/bin/app"

exit 0